# Generated by Django 3.2.5 on 2021-08-02 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100, null=True)),
                ('longitute', models.CharField(max_length=20, null=True)),
                ('latitute', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Territorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territorie_name', models.CharField(max_length=100, null=True)),
                ('longitute', models.CharField(max_length=20, null=True)),
                ('latitute', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('postcode', models.CharField(max_length=10, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territorie.region')),
            ],
        ),
    ]
