# Generated by Django 3.2.5 on 2021-08-02 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('territorie', '0001_initial'),
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='territorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='territorie.territorie'),
        ),
    ]
