# Generated by Django 3.2.5 on 2021-08-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorie', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='territorie',
            field=models.ManyToManyField(null=True, to='territorie.Territorie'),
        ),
    ]
